return {
    diagnostics = {
        Error = " ",
        Warn = " ",
        Hint = " ",
        Info = " ",
    },
    kinds = {
        Text = "󰉿",
        Method = "m",
        Function = "󰊕",
        Constructor = "",
        Field = "",
        Variable = "󰆧",
        Class = "󰌗",
        Interface = "",
        Module = "",
        Property = "",
        Unit = "",
        Value = "󰎠",
        Enum = "",
        Keyword = "󰌋",
        Snippet = "",
        Color = "󰏘",
        File = "󰈙",
        Reference = "",
        Folder = "󰉋",
        EnumMember = "",
        Constant = "󰇽",
        Struct = "",
        Event = "",
        Operator = "󰆕",
        TypeParameter = "󰊄",
    },
    todo = {
        todo = " ",
        hack = " ",
        warn = " ",
        perf = "󰅒 ",
        note = "󰍨 ",
        test = "⏲ ",
    },
    dbg = {
        disconnect = "",
        pause = "",
        play = "",
        run_last = "",
        step_back = "",
        step_into = "",
        step_out = "",
        step_over = "",
        terminate = "",
        expanded = "▾",
        collapsed = "▸",
        breakpoint = "",
        rejected = "",
        stopped = "",
        eval = "",
    },
    file = {
        folder_closed = "",
        folder_open = "",
        folder_empty = "󰜌",
    },
    git = {
        added = "",
        modified = "",
        deleted = "✖",
        renamed = "󰁕",
        -- Status type
        untracked = "",
        ignored = "",
        unstaged = "󰄱",
        staged = "",
        conflict = "",
    },
}
